# -*- coding: utf-8 -*-
"""dhauz_ticket_classifier_chroma_semantic_rag_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HS3I_rfrNLMtQ9stz-LY1TRhJaBRwIs3

# IT Service Ticket Classification — GenAI + RAG + Agents

Projeto para o desafio técnico **DHAUZ**.

Este notebook implementa três abordagens:

1. **Baseline clássico**
   - TF‑IDF + Logistic Regression

2. **Transformer**
   - DistilBERT fine‑tuned

3. **RAG + LLM**
   - ChromaDB vector store
   - Semantic RAG (retrieve only predicted class)
   - LangChain Agent

Pipeline principal:

ticket → DistilBERT class prediction → retrieve tickets of predicted class → LLM → JSON

## 1. Instalação de dependências
"""

!pip install -q kagglehub
!pip install -q transformers datasets accelerate evaluate
!pip install -q sentence-transformers
!pip install -q chromadb
!pip install -q langchain langchain-community
!pip install -q gradio nltk seaborn

!pip install -U langchain langchain-core langchain-community langchain-ollama langchain-chroma chromadb langchain-classic langchain-huggingface

"""## 2. Imports"""

import os
import json
import re
import string
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, cohen_kappa_score

"""## 3. Download dataset"""

import kagglehub

path = kagglehub.dataset_download(
    "adisongoh/it-service-ticket-classification-dataset"
)

print("Dataset path:", path)

df = pd.read_csv(os.path.join(path,"all_tickets_processed_improved_v3.csv"))

df = df.rename(columns={
    "Document":"text",
    "Topic_group":"class"
})

df.head()

"""## 4. Exploração"""

order = df['class'].value_counts(ascending=False).index
plt.figure(figsize=(12,7))

sns.countplot(x='class', data=df, order=order, palette='viridis', hue='class', legend=False)
plt.xticks(rotation=45, ha='right')
plt.title('Número de amostras por classe', fontsize=16)
plt.xlabel('Classe', fontsize=12)
plt.ylabel('Número de amostras', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

for p in plt.gca().patches:
    plt.annotate(f'{int(p.get_height())}', (p.get_x() + p.get_width() / 2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points', fontsize=10)
plt.tight_layout()
plt.show()

"""### Distribuição do Tamanho dos Tickets"""

df['text_length'] = df['text'].apply(len)

plt.figure(figsize=(12, 6))
sns.histplot(df['text_length'], bins=50, kde=True, color='skyblue')
plt.title('Distribuição do Tamanho dos Tickets', fontsize=16)
plt.xlabel('Número de Caracteres', fontsize=12)
plt.ylabel('Frequência', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Tamanho Médio dos Tickets por Classe"""

avg_length_per_class = df.groupby('class')['text_length'].mean().sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=avg_length_per_class.index, y=avg_length_per_class.values, palette='viridis', hue=avg_length_per_class.index, legend=False)
plt.xticks(rotation=45, ha='right')
plt.title('Tamanho Médio dos Tickets por Classe', fontsize=16)
plt.xlabel('Classe', fontsize=12)
plt.ylabel('Tamanho Médio do Texto', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

for p in plt.gca().patches:
    plt.annotate(f'{p.get_height():.1f}', (p.get_x() + p.get_width() / 2., p.get_height()), ha='center', va='center', xytext=(0, 10), textcoords='offset points', fontsize=10)
plt.tight_layout()
plt.show()

"""## 5. Split dataset"""

train, val = train_test_split(
    df,
    test_size=0.2,
    stratify=df["class"],
    random_state=42
)

test = val.sample(200,random_state=42)

print(len(train),len(val),len(test))

"""## 6. TF‑IDF + Logistic Regression"""

tfidf = TfidfVectorizer(max_features=10000,stop_words="english")

X_train = tfidf.fit_transform(train["text"])
X_val = tfidf.transform(val["text"])
X_test = tfidf.transform(test["text"])

y_train = train["class"]
y_val = val["class"]
y_test = test["class"]

clf = LogisticRegression(max_iter=1000,class_weight="balanced")
clf.fit(X_train,y_train)

val_pred = clf.predict(X_val)

print(classification_report(y_val,val_pred))
print("Cohen Kappa:",cohen_kappa_score(y_val,val_pred))

test_pred = clf.predict(X_test)

print(classification_report(y_test,test_pred))
print("Cohen Kappa:",cohen_kappa_score(y_test,test_pred))

"""## 7. DistilBERT"""

classes = sorted(train["class"].unique())
class_to_idx = {c:i for i,c in enumerate(classes)}

from transformers import DistilBertTokenizerFast
from transformers import DistilBertForSequenceClassification
from transformers import Trainer,TrainingArguments
from datasets import Dataset

train["label"] = train["class"].map(class_to_idx)
val["label"] = val["class"].map(class_to_idx)

train_ds = Dataset.from_pandas(train[["text","label"]])
val_ds = Dataset.from_pandas(val[["text","label"]])

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

def tokenize(example):
    return tokenizer(example["text"],padding="max_length",truncation=True, max_length=256)

train_ds = train_ds.map(tokenize,batched=True)
val_ds = val_ds.map(tokenize,batched=True)

train_ds.set_format("torch",columns=["input_ids","attention_mask","label"])
val_ds.set_format("torch",columns=["input_ids","attention_mask","label"])

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    # "./results/checkpoint-2392",
    num_labels=len(classes)
)

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=32,
    num_train_epochs=2,
    # report_to="none",
    logging_steps=100,
    fp16=True,
)

from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):

    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average="macro")

    return {
        "accuracy": acc,
        "f1": f1
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

test['label'] = test['class'].map(class_to_idx)
test_ds = Dataset.from_pandas(test[["text","label"]])
test_ds = test_ds.map(tokenize,batched=True)

val_pred_bert = trainer.predict(val_ds)
val_pred_bert = np.argmax(val_pred_bert.predictions, axis=1)

print(classification_report(val["label"],val_pred_bert))
print("Cohen Kappa:",cohen_kappa_score(val["label"],val_pred_bert))

test_pred_bert = trainer.predict(test_ds)
test_pred_bert = np.argmax(test_pred_bert.predictions, axis=1)

print(classification_report(test["label"],test_pred_bert))
print("Cohen Kappa:",cohen_kappa_score(test["label"],test_pred_bert))

"""## 8. Preprocessamento texto (RAG)"""

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess(text):

    text = text.lower()
    text = re.sub(r"http\S+","",text)
    text = text.translate(str.maketrans("","",string.punctuation))

    tokens = text.split()
    tokens = [t for t in tokens if t not in stop_words]
    tokens = [lemmatizer.lemmatize(t) for t in tokens]

    return " ".join(tokens)

train["clean_text"] = train["text"].apply(preprocess)

"""## 9. Chroma Vector Store"""

from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

docs = []

for _,row in train.iterrows():

    docs.append(
        Document(
            page_content=row["text"],
            metadata={
                "class":row["class"],
                "original_text":row["text"]
            }
        )
    )

embedding_model = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

vector_db = Chroma.from_documents(
    docs,
    embedding_model,
    persist_directory="./chroma_db"
)

"""## 10. Semantic RAG Retriever"""

import torch
import numpy as np


def bert_class_scores_batch(tickets):

    # garante lista
    if isinstance(tickets, str):
        tickets = [tickets]

    inputs = tokenizer(
        tickets,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    inputs = {k: v.to("cuda") for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    probs = torch.softmax(logits, dim=1).cpu().numpy()

    scores = []

    for prob in probs:
        scores.append(dict(zip(classes, prob)))

    return scores


def top_k_classes_batch(tickets, k=3):

    if isinstance(tickets, str):
        tickets = [tickets]

    scores_batch = bert_class_scores_batch(tickets)

    top_classes = []

    for scores in scores_batch:

        sorted_classes = sorted(
            scores.items(),
            key=lambda x: x[1],
            reverse=True
        )

        top_classes.append([c[0] for c in sorted_classes[:k]])

    return top_classes


def retrieve_examples_batch(tickets, k=3):

    # garante lista
    single_input = False
    if isinstance(tickets, str):
        tickets = [tickets]
        single_input = True

    top_classes = top_k_classes_batch(tickets, k)

    retrieved_examples = []

    for ticket, candidate_classes in zip(tickets, top_classes):

        examples = []

        for cls in candidate_classes:

            docs = vector_db.similarity_search(
                ticket,
                k=5,
                filter={"class": cls}
            )

            # garantir lista flat
            if isinstance(docs, list):
                examples.extend(docs)
            else:
                examples.append(docs)

        examples = sorted(
            examples,
            key=lambda d: d.metadata.get("score", 0),
            reverse=True
        )

        retrieved_examples.append(examples[:k])

    # se recebeu só um ticket, retorna só a lista de docs
    if single_input:
        return retrieved_examples[0]

    return retrieved_examples


def bert_topk_with_confidence(tickets, k=3):

    if isinstance(tickets, str):
        tickets = [tickets]

    scores_batch = bert_class_scores_batch(tickets)

    results = []

    for scores in scores_batch:

        sorted_classes = sorted(
            scores.items(),
            key=lambda x: x[1],
            reverse=True
        )

        top_classes = [c[0] for c in sorted_classes[:k]]
        top_probs = [c[1] for c in sorted_classes[:k]]

        results.append({
            "top_classes": top_classes,
            "top_probs": top_probs,
            "confidence": top_probs[0]
        })

    return results

"""## 11. LLM (Ollama)"""

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

# model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer_llm = AutoTokenizer.from_pretrained(model_name, padding_side='left')

model_llm = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.float16,
    device_map="auto"
)

from transformers import GenerationConfig

generation_config_ = GenerationConfig(
    do_sample=False,
    max_new_tokens=64,
    repetition_penalty=1.1
)

pipe = pipeline(
    "text-generation",
    model=model_llm,
    tokenizer=tokenizer_llm,
    config=generation_config_,
    return_full_text=False,
)

# from langchain_huggingface import HuggingFacePipeline, ChatHuggingFace

# llm_pipeline = HuggingFacePipeline(pipeline=pipe)

# llm = ChatHuggingFace(
#     llm=llm_pipeline
# )

torch.cuda.empty_cache()

"""## 12. RAG Classifier"""

import json
import re

def extract_json(text):

    matches = re.findall(r'\{[^{}]*\}', text)

    for m in matches:
        try:
            data = json.loads(m)

            if "class" in data and "justification" in data:
                return data

        except:
            continue

    return None

from langchain_core.messages import HumanMessage, SystemMessage

def rag_classifier_batch(tickets):
    prompts = []

    for ticket in tickets:

        retrieved = retrieve_examples_batch(ticket, k=3)
        examples = ""

        for doc in retrieved:

            examples += f"""
Ticket: {doc.metadata['original_text']}
Class: {doc.metadata['class']}
"""

        user_prompt = f"""Classify the IT support ticket.

Ticket:
{ticket}

Choose EXACTLY ONE category from:
{", ".join(classes)}

Return ONLY this JSON and NOTHING ELSE:

{{"class": "<category>", "justification": "<short reason>"}}
"""

        messages = [
            SystemMessage(
                content=f"""You are an AI assistant specialized in IT support ticket classification.

ONLY Possible categories:
{", ".join(classes)}

Examples:
{examples}
"""
            ),
            HumanMessage(content=user_prompt)
        ]

        prompt = tokenizer_llm.apply_chat_template(
            [
                {"role": "system", "content": messages[0].content},
                {"role": "user", "content": messages[1].content}
            ],
            tokenize=False,
            add_generation_prompt=True
        )

        prompts.append(prompt)

    outputs = pipe(
            prompts,
            batch_size=1,
            return_full_text=False
        )

    results = []

    for out in outputs:

        if isinstance(out, list):
            generated = out[0]["generated_text"]
        else:
            generated = out["generated_text"]

        parsed = extract_json(generated)

        if parsed is None or parsed["class"] not in classes:
            parsed = {
                "class": "Miscellaneous",
                "justification": "Invalid model output"
            }
        results.append(parsed)

    return results

from langchain_core.messages import HumanMessage, SystemMessage

def rag_classifier_batch_hybrid(tickets, candidate_classes_batch):

    prompts = []

    for ticket, candidate_classes in zip(tickets, candidate_classes_batch):

        retrieved = retrieve_examples_batch(ticket, k=3)

        examples = ""
        for doc in retrieved:
            examples += f"""
Ticket: {doc.metadata['original_text']}
Class: {doc.metadata['class']}
"""

        user_prompt = f"""Classify the IT support ticket.

Ticket:
{ticket}

Choose EXACTLY ONE category from:

1. {candidate_classes[0]}
2. {candidate_classes[1]}
3. {candidate_classes[2]}

Return ONLY this JSON:

{{"class": "<category>", "justification": "<short reason>"}}
"""

        messages = [
            SystemMessage(
                content=f"""You are an AI assistant specialized in IT support ticket classification.

Possible categories:
{", ".join(candidate_classes)}

Examples:
{examples}
"""
            ),
            HumanMessage(content=user_prompt)
        ]

        prompt = tokenizer_llm.apply_chat_template(
            [
                {"role": "system", "content": messages[0].content},
                {"role": "user", "content": messages[1].content}
            ],
            tokenize=False,
            add_generation_prompt=True
        )

        prompts.append(prompt)

    outputs = pipe(
        prompts,
        batch_size=1,
        return_full_text=False
    )

    results = []

    for out in outputs:

        if isinstance(out, list):
            generated = out[0]["generated_text"]
        else:
            generated = out["generated_text"]

        parsed = extract_json(generated)

        if parsed is None:
            parsed = {
                "class": "Miscellaneous",
                "justification": "Invalid model output"
            }

        results.append(parsed)

    return results

def hybrid_classifier_batch(tickets, threshold=0.9):

    bert_results = bert_topk_with_confidence(tickets)

    final_results = []
    rag_tickets = []
    rag_classes = []
    rag_indices = []

    for i, (ticket, bert_res) in enumerate(zip(tickets, bert_results)):

        confidence = bert_res["confidence"]
        top_classes = bert_res["top_classes"]

        if confidence >= threshold:

            final_results.append({
                "class": top_classes[0],
                "justification": "High confidence DistilBERT prediction"
            })

        else:

            rag_tickets.append(ticket)
            rag_classes.append(top_classes)
            rag_indices.append(i)

            final_results.append(None)

    if len(rag_tickets) > 0:

        rag_outputs = rag_classifier_batch_hybrid(
            rag_tickets,
            rag_classes
        )

        for idx, rag_out in zip(rag_indices, rag_outputs):
            final_results[idx] = rag_out

    return final_results

def rag_predict_batch(batch):

    results = rag_classifier_batch(batch["text"])

    return {
        "prediction": [r["class"] for r in results],
        "justification": [r["justification"] for r in results]
    }

def hybrid_predict_batch(batch):

    results = hybrid_classifier_batch(batch["text"])

    return {
        "prediction": [r["class"] for r in results],
        "justification": [r["justification"] for r in results]
    }

"""## 13. LangChain Agent"""

from langchain.agents import create_agent
from langchain_classic.agents import AgentExecutor
from langchain_core.tools import StructuredTool

tool = StructuredTool.from_function(
    func=rag_classifier_batch,
    name="IT_Ticket_Classifier",
    description="Classify an IT support ticket into predefined categories"
)

tools = [tool]

system_prompt = """
You are an AI assistant specialized in IT support ticket classification.

When a user sends a ticket:
1. Always call the IT_Ticket_Classifier tool
2. Return the JSON result from the tool without modification.
"""

agent = create_agent(
    model=llm,
    tools=tools,
    system_prompt=system_prompt
)

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True
)

"""## 14. Teste do Agent"""

ticket = "User cannot connect to VPN after password reset"

result = rag_classifier_batch([ticket,'access to oracle and wednesday november pm dear please create please viewer role planner well add level thanks kind regards officer november re approved wednesday november pm hi want please reports kindly approve thanks head november wait re hi level looking how call solution client level approve well own requests each license implication consider skip training how give extracts work part well kind regards officer november wait hi told help budgeting application view onto appreciate lot help available find thank much senior blvd fax subscribe notified about events publications choice please consider environment printing'])

print(result)

hf_test = test_ds.map(
    rag_predict_batch,
    batched=True,
    batch_size=1,
    desc="Running RAG classifier"
)

hf_test = test_ds.map(
    hybrid_predict_batch,
    batched=True,
    batch_size=1,
    desc="Running RAG classifier"
)

test = test.reset_index(drop=True)

hf_test_df = hf_test.to_pandas().reset_index(drop=True)

test["prediction"] = hf_test_df["prediction"]
test["justification"] = hf_test_df["justification"]

for i, row in test.iterrows():
    if row['justification'] == 'Invalid model output':
        print(i)
        tries = 0
        while tries < 3:
            result = rag_classifier_batch([row['text']])[0]

            if result['justification'] != 'Invalid model output':
                break

            tries += 1
        print(row['class'], result['class'], result['justification'])
        test.at[i, 'prediction'] = result['class']
        test.at[i, 'justification'] = result['justification']

test

from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(
    test["class"],
    test["prediction"],
    labels=classes
)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=classes,
    yticklabels=classes
)

print(
    classification_report(
        test["class"],
        test["prediction"],
        # zero_division=0,
        labels=classes
    )
)

"""## 15. Interface Gradio"""

def rag_classifier(ticket):
    result = rag_classifier_batch([ticket])[0]

    return result['class'], result['justification']

def rag_classifier_v2(ticket):
    result = hybrid_classifier_batch([ticket])[0]

    return result['class'], result['justification']

import gradio as gr

demo = gr.Interface(
    fn=rag_classifier,
    inputs=gr.Textbox(
        lines=4,
        label="IT Support Ticket"
    ),
    outputs=[
        gr.Label(label="Predicted Class"),
        gr.Textbox(label="Justification")
    ],
    examples=[
        "User cannot connect to VPN after password reset",
        "Laptop screen broken need replacement",
        "Create account for new employee",
        "Need access to Oracle reports"
    ],
    title="IT Ticket Classifier (RAG)",
    description="Hybrid classifier using DistilBERT + Retrieval + LLM reasoning."
)

demo.launch()
